# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn.datasets import load_iris
x = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X=x.data
y=x.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
test_size = 0.30
seed = 7 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [7]:
from keras.utils import to_categorical
y_train=to_categorical(y_train,num_classes=3)
y_test=to_categorical(y_test,num_classes=3)

Using TensorFlow backend.


## Question 5

### Initialize a sequential model
- Define a sequential model

The sequential API allows you to create models layer-by-layer for most problems. It is limited in that it does not allow you to create models that share layers or have multiple inputs or outputs.

In [0]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3,input_shape=(4,),activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [12]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100)

Train on 105 samples, validate on 45 samples
Epoch 1/100
105/105 [==============================] - 1s 5ms/sample - loss: 2.6249 - accuracy: 0.3619 - val_loss: 2.0676 - val_accuracy: 0.2667
Epoch 2/100
105/105 [==============================] - 0s 215us/sample - loss: 1.6649 - accuracy: 0.3619 - val_loss: 1.4904 - val_accuracy: 0.1556
Epoch 3/100
105/105 [==============================] - 0s 293us/sample - loss: 1.3363 - accuracy: 0.2000 - val_loss: 1.3252 - val_accuracy: 0.0222
Epoch 4/100
105/105 [==============================] - 0s 230us/sample - loss: 1.2434 - accuracy: 0.0857 - val_loss: 1.2319 - val_accuracy: 0.2000
Epoch 5/100
105/105 [==============================] - 0s 247us/sample - loss: 1.1763 - accuracy: 0.1905 - val_loss: 1.1825 - val_accuracy: 0.2444
Epoch 6/100
105/105 [==============================] - 0s 214us/sample - loss: 1.1343 - accuracy: 0.2381 - val_loss: 1.1206 - val_accuracy: 0.2667
Epoch 7/100
105/105 [==============================] - 0s 212us/sample - lo

## Question 10

### Make predictions
- Predict labels on one row

In [13]:
model.predict(X_test[:1])

array([[0.02452511, 0.3225293 , 0.65294564]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [14]:
print(y_test[:1])

[[0. 0. 1.]]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [16]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
from google.colab import drive

In [19]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/Colab/prices-1.csv')
df

date symbol  ...        high     volume
0       2016-01-05 00:00:00   WLTW  ...  126.250000  2163600.0
1       2016-01-06 00:00:00   WLTW  ...  125.540001  2386400.0
2       2016-01-07 00:00:00   WLTW  ...  119.739998  2489500.0
3       2016-01-08 00:00:00   WLTW  ...  117.440002  2006300.0
4       2016-01-11 00:00:00   WLTW  ...  117.330002  1408600.0
...                     ...    ...  ...         ...        ...
851259           2016-12-30    ZBH  ...  103.930000   973800.0
851260           2016-12-30   ZION  ...   43.310001  1938100.0
851261           2016-12-30    ZTS  ...   53.740002  1701200.0
851262  2016-12-30 00:00:00    AIV  ...   45.590000  1380900.0
851263  2016-12-30 00:00:00    FTV  ...   54.480000   705100.0

[851264 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
df.drop(columns=['date','symbol'],inplace=True)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [22]:
df1=df.head(1000)
df1

open       close         low        high      volume
0    123.430000  125.839996  122.309998  126.250000   2163600.0
1    125.239998  119.980003  119.940002  125.540001   2386400.0
2    116.379997  114.949997  114.930000  119.739998   2489500.0
3    115.480003  116.620003  113.500000  117.440002   2006300.0
4    117.010002  114.970001  114.089996  117.330002   1408600.0
..          ...         ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999   2133200.0
996   27.160000   26.990000   26.680000   27.299999   1982400.0
997   28.320000   28.770000   28.010000   28.809999  37152800.0
998   44.000000   44.799999   43.750000   44.810001   6568600.0
999   36.080002   37.139999   36.009998   37.230000   5604300.0

[1000 rows x 5 columns]

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
y=df1['volume']/1000000
X=df1[(['open','close','low','high'])]

In [27]:
y

0       2.1636
1       2.3864
2       2.4895
3       2.0063
4       1.4086
        ...   
995     2.1332
996     1.9824
997    37.1528
998     6.5686
999     5.6043
Name: volume, Length: 1000, dtype: float64

In [28]:
X

open       close         low        high
0    123.430000  125.839996  122.309998  126.250000
1    125.239998  119.980003  119.940002  125.540001
2    116.379997  114.949997  114.930000  119.739998
3    115.480003  116.620003  113.500000  117.440002
4    117.010002  114.970001  114.089996  117.330002
..          ...         ...         ...         ...
995   63.310001   63.590000   63.240002   63.639999
996   27.160000   26.990000   26.680000   27.299999
997   28.320000   28.770000   28.010000   28.809999
998   44.000000   44.799999   43.750000   44.810001
999   36.080002   37.139999   36.009998   37.230000

[1000 rows x 4 columns]

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
import numpy as np
X=np.array(X).astype('float32')
y=np.array(y).astype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X = tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function
def prediction(X, W, b):
    y_pred = tf.add(tf.matmul(X,W), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function
def loss(y, y_pred):
    diff = y- y_pred
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
@tf.function
def train(X, y, W, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([W,b])
        current_prediction = prediction(X, W, b)
        current_loss = loss(y, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[W, b])
    
    # Update Weights and Bias
    W = W - learning_rate * dw
    b = b - learning_rate * db
    
    return W, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [36]:
for i in range(100):    
    W, b = train(X, y, W, b)
    print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11781
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67297
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44553
Current Training Loss on iteration 15 223.835
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68655
Current Training Loss on iteration 18 222.14595
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [37]:
W.numpy()

array([[0.0547828 ],
       [0.05488191],
       [0.05422735],
       [0.05533117]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [38]:
b.numpy()

array([4.607657], dtype=float32)